language: node_js
node_js:
  - "8"
install:
  - npm install -g firebase-tools
  - npm install -g @vue/cli-service-global
script:
  - npm run build
after_success:
  - firebase deploy --project games-2b64c --token $FIREBASE_TOKEN
