language: node_js
node_js:
  - "8"
install:
  - npm install -g firebase-tools
before_script:
  - yarn global add @vue/cli
script:
  - npm run build -- --prod
after_success:
  - firebase deploy --project games-2b64c --token $FIREBASE_TOKEN
