language: node_js
node_js:
  - "12"
install:
  - npm install -g firebase-tools
  - npm uninstall -g vue-cli
  - npm install -g @vue/cli
script:
  - npm run build
after_success:
  - firebase deploy --project games-2b64c --token $FIREBASE_TOKEN
